<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [72]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    
 
    if (len(A[0])!=len(B)):
      print("matrix multiplication not possible")
    else:
      res=[[0 for x in range(len(B[0]))] for j in range(len(A))]
      for arow in range(len(A)):
        for bcol in range(len(B[0])):
          for k in range(len(B)):
            res[arow][bcol]= ((res[arow][bcol])+(A[arow][k]*B[k][bcol]))  
         

    return(res)

A= [[1,3,4],
    [2 ,5 ,7],
    [5 ,9 ,6]]  
B=[[1 ,0 ,0],
   [0 ,1, 0],
   [0,0,1]]

result=matrix_mul(A, B)
print(result)

##creditss--geeks for geeks===https://www.geeksforgeeks.org/nested-list-comprehensions-in-python/



[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


:<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [33]:
from random import uniform
import numpy as np
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #calculating sum
    sum=0
    for i in A:
      sum=sum+i

    #calculating cumulative frequencies
    x=0
    list1=[]
    for i in A:
      list1.append(x+i/sum)
      x=x+i/sum
    random_val=np.random.uniform(0.0,1.0,1)   
    for i in range (0,len(list1)):
      if random_val>=list1[i] and random_val<list1[i+1]:
        return(A[i+1])
  
def sampling_based_on_magnitued():
    A = [0, 5 ,27, 6 ,13, 28, 100, 45 ,10, 79] 
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

print(sampling_based_on_magnitued())

##ref---stackoverflow

79
100
79
79
79
100
100
100
28
6
45
45
100
27
79
100
100
79
45
45
100
79
45
100
79
6
45
79
27
79
79
79
100
100
45
45
79
100
45
28
28
100
100
79
100
27
100
100
27
13
13
79
27
28
79
79
27
79
45
27
28
100
79
79
100
28
28
28
13
27
28
79
10
100
100
27
79
100
79
100
79
100
45
100
100
100
27
79
45
79
13
100
45
79
27
100
27
100
27
None


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    str=""
    for character in String:
      if character.isdigit():
        str=str+"#"

    return(str) # modified string which is after replacing the # with digits
String="#2a$#b%c%561#"
str=replace_digits(String)
print(str)

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
import numpy as np
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    dic={}
    val_25=0.0
    val_75=0.0
    students_within_25_and_75=[]
    top_5_students=0
    least_5_students=0
    
    for i in range(len(students)):
      dic[students[i]]=marks[i]
    sorted_dict = sorted({(value, key)for (key, value) in dic.items()},reverse=True)
    y=dict(sorted_dict)
    top_5_students = sorted_dict[:5]
    # write code for computing top least 5 students

    least_5_students =sorted_dict[-5:]
    # write code for computing top least 5 students
    val_25=np.percentile(len(marks),25)
    val_75=np.percentile(len(marks),75)
    for i,j  in y.items():
      if (i>val_25 and i<val_75):
        students_within_25_and_75.append(i)   
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
top_5_students, least_5_students, students_within_25_and_75

([(98, 'student8'),
  (80, 'student10'),
  (78, 'student2'),
  (48, 'student5'),
  (47, 'student7')],
 [(45, 'student1'),
  (43, 'student6'),
  (22, 'student9'),
  (14, 'student4'),
  (12, 'student3')],
 [])

<h3> Q5: Find the closest points</h3>

*   List item
*   List item



Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [71]:
import math
import numpy as np


# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    distances=[]
    least_dist=[]
    li=[]
    squarepoint=0.0
    dist=0.0
    commonpoint=((P[0]**2)+(P[1]**2))
    for point in S:
      squarepoint=((point[0]**2)+(point[1]**2))
      p=((point[0]*P[0])+(point[1]*P[1]))
     
      dist=((p)/(math.sqrt(commonpoint*squarepoint)))
      cos_dist= math.acos(dist)
         #applying cos-1 function
      distances.append(cos_dist)
    for i in range(5):
      li.append(S[distances.index(min(distances))])
      distances[distances.index(min(distances))]=100
    return li 

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values(6,-7)


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [25]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
  red_vals=[]
  blue_vals=[]
  if line[0]=='-':
    x_coeff=int(line[1])*-1
  else:
    x_coeff=int(line[0])
  
  index_y=line.index('y')
  if line[index_y-2]== '-':
    y_coeff=int(line[index_y-1])*(-1)
  else:
    y_coeff=int(line[index_y-1])
  
  if i[-2]=='-':
      intercept=int(line[-1])*-1
  if i[-2]=='.':
      intercept=float(line[-1])/(10)    
  else:
      intercept=int(line[-1])   
  
  for point in red:
    red_vals.append((point[0]*x_coeff)+(point[1]*y_coeff+intercept))    


  for point in blue:
    blue_vals.append((point[0]*x_coeff)+(point[1]*y_coeff+intercept))    
      
  if ((all(x >= 0 for x in red_vals)) and (all(y <=0 for y in blue_vals))):
     return True
    
  if ((all(x <= 0 for x in red_vals)) and (all(x >= 0 for x in blue_vals))):
    return True
  else:
    return False
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

True
False
False
True


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [114]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
  li=[]
  li=string.split(",")
  l = list(map(lambda x: x.replace('_', '0'), li))
  res=[int(i) for i in l]
  min_term=0
  for idx in range(len(res)):
    if res[idx]>0 or idx==len(res)-1:
      p=idx-min_term+1
      value=(res[min_term]+res[idx])/p
      for kk in range(min_term,idx+1):
         res[kk]=value
      min_term=idx
    # your code
    



   

  return res


S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [68]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
  d={}
  p={}
  u={} 
  l={}
  for x in A:
    sval=x[1]
    d[sval] = d.get(sval,0) + 1
  s1=[]
  s2=[]
  s3=[]
  for i in A:
    if i[1]=="S1":
      s1.append(i[0])
    if i[1]=="S2":
      s2.append(i[0])
    if i[1]=="S3":
      s3.append(i[0])  
  sorted(s1)
  sorted(s2)
  sorted(s3)
  for i in s1:
    p[i] = p.get(i,0) + 1
    print("probability of F={} / S=S1={}/{}".format(i,p[i],d['S1']))
  for i in s2:
    u[i] = u.get(i,0) + 1
    print("probability of F={} / S=S2={}/{}".format(i,u[i],d['S2']))   
  for i in s3:
    l[i] = l.get(i,0) + 1
    print("probability of F={} / S=S3={}/{}".format(i,l[i],d['S3']))
  
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

probability of F=F1 / S=S1=1/4
probability of F=F2 / S=S1=1/4
probability of F=F4 / S=S1=1/4
probability of F=F5 / S=S1=1/4
probability of F=F2 / S=S2=1/3
probability of F=F1 / S=S2=1/3
probability of F=F3 / S=S2=1/3
probability of F=F3 / S=S3=1/3
probability of F=F2 / S=S3=1/3
probability of F=F4 / S=S3=1/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    a=0
    b=[]
    c=[]
    list_1=S1.split(" ")
    list_2=S2.split(" ")
    for i in list_1:
      if i in list_2:
        a=a+1
      else:
        b.append(i)  
    for i in list_2:
      if i not in list_1:
        c.append(i)
              

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("no of common words are {}".format(a))
print("b.{}".format(b))
print("c.{}".format(c))

no of common words are 7
b.['first', 'F', '5']
c.['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
from logging import log
from logging import log
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    loss=0.0
    sum=0.0
    res_each_pair=0.0
    n=len(A)
    for each_pair in A:
      res_each_pair=((each_pair[0]*math.log10(each_pair[1]))+((1-each_pair[0])*math.log10(1-each_pair[1])))
      
      sum=sum+ res_each_pair
      
    loss=((-1)/n)*sum


    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
